#!/bin/zsh

local rez_dir=/Volumes/path/to/rez

# use the custom rez settings
export REZ_CONFIG_FILE=$rez_dir/config/rezconfig.py

# this enables extending the packages path at runtime like:
# export REZ_PACKAGES_PATH=/some/path/to/packages:$REZ_PACKAGES_PATH
export REZ_PACKAGES_PATH=~/packages:$rez_dir/packages/int:$rez_dir/packages/ext:$rez_dir/packages/python

# create the cache directory
mkdir -p ~/rez_cache

# enable rez
rez_path=$rez_dir/osx/bin/rez
if [ -f ~/Applications/rez/bin/rez/.rez_production_install ]; then
    # use the local rez install for better performance
    rez_path=~/Applications/rez/bin/rez
fi

export PATH=$rez_path:$PATH
