#!/usr/bin/bash

set rez_dir=/path/to/rez

# use the custom rez settings
export REZ_CONFIG_FILE=$rez_dir/config/rezconfig.py

# this enables extending the packages path at runtime like:
# export REZ_PACKAGES_PATH=/some/path/to/packages:$REZ_PACKAGES_PATH
export REZ_PACKAGES_PATH=~/packages:$rez_dir/packages/int:$rez_dir/packages/ext:$rez_dir/packages/python

# enable rez
export PATH=$rez_dir/linux/bin/rez:$PATH

